# Generated by Django 5.0.7 on 2024-09-03 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nome_user',
            name='cpf',
            field=models.CharField(default=1.0, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nome_user',
            name='data_atual',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
