# Generated by Django 5.1.1 on 2024-09-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_comment_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='text_title',
            field=models.CharField(default=1.0, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='text_profile',
            field=models.CharField(max_length=350),
        ),
    ]
